POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3RlciIsImlkIjoiNjFlNmUyNzAwMGRhMmQ3MWZiOGJjYzdjIiwiaWF0IjoxNjQyNTIxMjI1LCJleHAiOjE2NDI1MjQ4MjV9.zB8ugobQQ-4bUfYhRtMOWWrsD-DNcN1GPXny42WaK2g

{
    "title": "Blog to delete",
    "author": "Yea",
    "url": "proger.io",
    "likes": 10
}